# Generated by Django 4.2.16 on 2024-10-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_date_alter_customuser_dojo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ニックネーム', 'verbose_name_plural': 'ニックネーム'},
        ),
        migrations.AlterModelOptions(
            name='dojo',
            options={'verbose_name': '道場', 'verbose_name_plural': '道場'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント', 'verbose_name_plural': 'イベント'},
        ),
        migrations.AlterModelOptions(
            name='eventjoin',
            options={'verbose_name': 'イベント参加情報', 'verbose_name_plural': 'イベント参加情報'},
        ),
        migrations.AlterModelOptions(
            name='examinationresult',
            options={'verbose_name': '審査結果', 'verbose_name_plural': '審査結果'},
        ),
        migrations.AlterModelOptions(
            name='practicerecord',
            options={'verbose_name': '稽古記録', 'verbose_name_plural': '稽古記録'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': '階級', 'verbose_name_plural': '階級'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.PositiveIntegerField(default=0, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=40, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='name',
            field=models.CharField(max_length=40, verbose_name='道場名'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=40, verbose_name='イベント'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=200, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teachername',
            field=models.CharField(max_length=50, verbose_name='指導者名'),
        ),
        migrations.AlterField(
            model_name='eventjoin',
            name='status',
            field=models.IntegerField(verbose_name='イベント参加情報'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='examinationdate',
            field=models.DateTimeField(verbose_name='審査日'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='result',
            field=models.IntegerField(verbose_name='審査結果'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='updatedate',
            field=models.DateTimeField(verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='practicecontents',
            field=models.TextField(verbose_name='稽古内容'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='practicedate',
            field=models.DateField(verbose_name='稽古日時'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='updatedate',
            field=models.DateTimeField(verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(max_length=10, verbose_name='階級'),
        ),
    ]
