# Generated by Django 4.2.16 on 2024-10-18 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_favorite_options_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
