# Generated by Django 4.2.16 on 2024-10-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_favorite_options_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'お気に入り', 'verbose_name_plural': 'お気に入り'},
        ),
    ]
