# Generated by Django 4.2.16 on 2024-10-19 11:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_contents_alter_event_dojo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dojo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.dojo', verbose_name='所属道場'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rank', verbose_name='登録時の階級'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='introduction',
            field=models.TextField(verbose_name='紹介文'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='mailaddress',
            field=models.EmailField(max_length=100, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='eventjoin',
            name='canceldate',
            field=models.DateTimeField(verbose_name='キャンセル日時'),
        ),
        migrations.AlterField(
            model_name='eventjoin',
            name='reservationdate',
            field=models.DateTimeField(verbose_name='予約日時'),
        ),
        migrations.AlterField(
            model_name='eventjoin',
            name='updatedate',
            field=models.DateTimeField(verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rank', verbose_name='階級'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='イベント名'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rank', verbose_name='階級'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
    ]
