# Generated by Django 4.2.16 on 2024-10-19 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customuser_date_alter_customuser_dojo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventjoin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='イベント名'),
        ),
        migrations.AlterField(
            model_name='eventjoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
    ]
